---
- name: fail on unsupported init systems
  fail:
    msg: "This module only works with systemd"
  when: ansible_service_mgr != 'systemd'

- name: "get checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
  set_fact:
    __haproxy_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', 'https://github.com/prometheus/haproxy_exporter/releases/download/v' + haproxy_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture)) + '.tar.gz') in item"
